baseURL = "https://b1ve01.github.io/"
languageCode = "en-us"
title = "blue_blog"
theme = "terminal"

[params]
  # 重点：主题色
  themeColor = "white"
  contentTypeName = "posts"

  # --- 必须这样写才能改掉左上角的字 ---
  [params.logo]
    logoText = "hello,world!"      # 这里改成你想要的字
    logoCursor = "_"      # 这里是后面的闪烁光标
  # ----------------------------------

  [[params.menu.main]]
    name = "Network"
    url = "/posts/?config=network"
  [[params.menu.main]]
    name = "Linux"
    url = "/posts/?config=linux"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"